### ISSUE TITLE
Packages status?

### ISSUE THREAD

**Issue by Sivli-Embir** [artwells/meteor-queue#4]
I am now using this package to mange [Heralds](https://github.com/Meteor-Reaction/Herald) server side media :) 

I would love some of the tools in your TODO. What is your timing looking like? Are you still actively working on this?

**Comment by artwells** [comment]
I've added instructions on the README to include how to use houston:admin to run/edit tasks in the queue.  Didn't think it merited a version change, but thought you might be interested.

**Comment by Kestanous** [comment]
That is a fun trick. I will play around with it soon, thanks for the tip.

**Comment by artwells** [comment]
I also hoped to a put a "purge all" button, at least on the log collection, but I see that that is a feature request on houston:admin, so will probably work towards that upstream.
