### ISSUE TITLE
Failed lock attempts should be purged according to lock purge rules

### ISSUE THREAD

**Issue by oskarszoon** [artwells/meteor-queue#5]
Currently if a lock fails a log item is created with status "lockfailed", they currently only get purged when purgeOldLogs is called (which has a default timeout of 30 days).

I believe these items should be cleaned according to the lock rules (which is 30 minutes) and purged together with purgeOldLocks.

In our case we had 300k+ queue items with status lockfailed (because of a different issue).

**Comment by Kestanous** [comment]
@artwells would you mind publishing v0.0.4? Its not on atmo at the moment.

**Comment by artwells** [comment]
Sorry about that.  It should be there now.

**Comment by artwells** [comment]
Also,  the next version of houston:admin should have a "Delete all" button for purging collections
